google.maps.__gjsload__('infowindow', function(_){var EMa=function(a,b){if(a.qh.size===1){let c=Array.from(a.qh.values())[0];c.ct!==b.ct&&(c.set("map",null),a.qh.delete(c))}a.qh.add(b)},GMa=function(a,b,c=!1){var d=a.__gm;a=d.get("panes");d=d.get("innerContainer");b={nn:a,Ij:_.BB.Ij(),FA:d,shouldFocus:b,ct:c};return new FMa(b)},ZK=function(a,b){a.container.style.visibility=b?"":"hidden";b&&a.shouldFocus&&(a.focus(),a.shouldFocus=!1);b?HMa(a):a.Ch=!1},IMa=function(a){a.Oj.setAttribute("aria-labelledby",a.th.id)},JMa=function(a){var b=!!a.get("open"),
c=a.get("content");c=b?c:null;if(c===a.xh)ZK(a,b&&a.get("position"));else{if(a.xh){let d=a.xh.parentNode;d===a.qh&&d.removeChild(a.xh)}c&&(a.Bh=!1,a.qh.appendChild(c));ZK(a,b&&a.get("position"));a.xh=c;$K(a)}},aL=function(a){var b=!!a.get("open"),c=a.get("headerContent"),d=!!a.get("ariaLabel"),e=a.get("headerDisabled"),f=!!a.get("isPoi"),g=!e;b=b?c:null;c=f&&e;a.Oj.style.paddingTop=!f&&e?"12px":"0";e=a.Oj;c?_.ow(e,"gm-style-iw-poi"):_.SE(e,"gm-style-iw-poi");_.Lp.qh&&!_.Lp.zh&&(a.qh.style.overflow=
c?"auto":"scroll");b===a.zh?a.sh.style.display=g?"":"none":(a.zh&&(e=a.zh.parentNode,e===a.th&&e.removeChild(a.zh)),b&&(a.Bh=!1,a.th.appendChild(b),g&&!d&&IMa(a)),a.sh.style.display=g?"":"none",a.zh=b,$K(a))},bL=function(a,b){var c=!!a.get("isPoi");a=!!a.get("headerDisabled");c&&a&&b instanceof HTMLElement&&(b.style.outline="none");return _.Sp(b,!0)},$K=function(a){var b=a.getSize();if(b){var c=b.oo;b=b.minWidth;a.Oj.style.maxWidth=_.nm(c.width);a.Oj.style.maxHeight=_.nm(c.height);a.Oj.style.minWidth=
_.nm(b);b=!!a.get("headerDisabled");b=!!a.get("isPoi")&&b;a.qh.style.maxHeight=_.Lp.qh?_.nm(c.height-(b?0:18)):_.nm(c.height-(b?0:36));cL(a);a.Ah.start()}},KMa=function(a){var b=a.get("pixelOffset")||new _.eo(0,0),c=new _.eo(a.Oj.offsetWidth,a.Oj.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;b.height<0&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},HMa=function(a){!a.Ch&&a.get("open")&&a.get("visible")&&a.get("position")&&(_.un(a,
"visible"),a.Ch=!0)},cL=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=KMa(a);let d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.sw(a.anchor,b);b=a.get("zIndex");_.uw(a.container,_.dm(b)?b:e+60);a.set("pixelBounds",_.xo(d,e,f,c))}},MMa=function(a,b,c){return b instanceof _.Jn?new LMa(a,b,c):new LMa(a,b)},OMa=function(a){a.qh&&a.Pi.push(_.sn(a.qh,"pixelposition_changed",()=>{NMa(a)}))},NMa=function(a){var b=a.model.get("pixelPosition")||a.qh&&a.qh.get("pixelPosition");
a.th.set("position",b)},QMa=function(a){a=a.__gm;a.get("IW_AUTO_CLOSER")||a.set("IW_AUTO_CLOSER",new PMa);return a.get("IW_AUTO_CLOSER")},PMa=class{constructor(){this.qh=new Set}};var FMa=class extends _.wn{constructor(a){super();this.xh=this.zh=this.yh=null;this.Ch=this.Bh=!1;this.FA=a.FA;this.shouldFocus=a.shouldFocus;this.container=document.createElement("div");this.container.style.cursor="default";this.container.style.position="absolute";this.container.style.left=this.container.style.top="0";a.nn.floatPane.appendChild(this.container);this.anchor=document.createElement("div");this.container.appendChild(this.anchor);this.wh=document.createElement("div");this.anchor.appendChild(this.wh);
this.Oj=document.createElement("div");this.wh.appendChild(this.Oj);this.Oj.setAttribute("role","dialog");this.Oj.tabIndex=-1;this.sh=document.createElement("div");this.Oj.appendChild(this.sh);this.th=document.createElement("div");this.sh.appendChild(this.th);this.Fh=document.createElement("div");this.wh.appendChild(this.Fh);this.qh=document.createElement("div");this.Oj.appendChild(this.qh);_.oDa(this.container);_.ow(this.Oj,"gm-style-iw");_.ow(this.anchor,"gm-style-iw-a");_.ow(this.wh,"gm-style-iw-t");
_.ow(this.Fh,"gm-style-iw-tc");_.ow(this.Oj,"gm-style-iw-c");_.ow(this.sh,"gm-style-iw-chr");_.ow(this.th,"gm-style-iw-ch");_.ow(this.qh,"gm-style-iw-d");this.set("isPoi",a.ct);this.th.setAttribute("id",_.In());_.Lp.qh&&!_.Lp.zh&&(this.Oj.style.paddingInlineEnd="0",this.Oj.style.paddingBottom="0",this.qh.style.overflow="scroll");ZK(this,!1);_.on(this.container,"mousedown",_.fn);_.on(this.container,"mouseup",_.fn);_.on(this.container,"mousemove",_.fn);_.on(this.container,"pointerdown",_.fn);_.on(this.container,
"pointerup",_.fn);_.on(this.container,"pointermove",_.fn);_.on(this.container,"dblclick",_.fn);_.on(this.container,"click",_.fn);_.on(this.container,"touchstart",_.fn);_.on(this.container,"touchend",_.fn);_.on(this.container,"touchmove",_.fn);_.fw(this.container,"contextmenu",this,this.Gh);_.fw(this.container,"wheel",this,_.fn);a=new _.$n(12,12);var b=new _.eo(24,24);this.rh=new _.Rq({Zs:a,Gu:b,offset:new _.$n(-6,-6),iF:!0,ownerElement:this.sh});this.sh.appendChild(this.rh.element);_.on(this.rh.element,
"click",c=>{_.fn(c);_.un(this,"closeclick");this.set("open",!1)});this.Ah=new _.yp(()=>{!this.Bh&&this.get("content")&&this.get("visible")&&(_.un(this,"domready"),this.Bh=!0)},0);this.Dh=_.on(this.container,"keydown",c=>{c.key!=="Escape"&&c.key!=="Esc"||!this.Oj.contains(document.activeElement)||(c.stopPropagation(),_.un(this,"closeclick"),this.set("open",!1))})}ariaLabel_changed(){var a=this.get("ariaLabel");a?this.Oj.setAttribute("aria-label",a):(this.Oj.removeAttribute("aria-label"),this.get("headerDisabled")||
IMa(this))}open_changed(){JMa(this);aL(this)}headerContent_changed(){aL(this)}headerDisabled_changed(){aL(this)}content_changed(){JMa(this)}pendingFocus_changed(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?bL(this,this.Oj):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))}dispose(){setTimeout(()=>{document.activeElement&&document.activeElement!==document.body||
(this.yh&&this.yh!==document.body?bL(this,this.yh)||bL(this,this.FA):bL(this,this.FA))});this.Dh&&_.kn(this.Dh);this.container.parentNode.removeChild(this.container);this.Ah.stop();this.Ah.dispose()}getSize(){var a=this.get("layoutPixelBounds"),b=this.get("pixelOffset"),c=this.get("maxWidth")||648,d=this.get("minWidth")||0;if(!b)return null;a?(b=a.maxY-a.minY-(11+-b.height),a=a.maxX-a.minX-6,a>=240&&(a-=120),b>=240&&(b-=120)):(a=648,b=654);a=Math.min(a,c);a=Math.max(d,a);a=Math.max(0,a);b=Math.max(0,
b);return{oo:new _.eo(a,b),minWidth:d}}pixelOffset_changed(){var a=this.get("pixelOffset")||new _.eo(0,0);this.wh.style.right=_.nm(-a.width);this.wh.style.bottom=_.nm(-a.height+11);$K(this)}layoutPixelBounds_changed(){$K(this)}position_changed(){this.get("position")?(cL(this),ZK(this,!!this.get("open"))):ZK(this,!1)}zIndex_changed(){cL(this)}visible_changed(){this.container.style.display=this.get("visible")?"":"none";this.Ah.start();if(this.get("visible")){let a=this.rh.element.style.display;this.rh.element.style.display=
"none";this.rh.element.getBoundingClientRect();this.rh.element.style.display=a;HMa(this)}else this.Ch=!1}Gh(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d===c,d=d.parentNode;b?_.an(a):_.en(a)}focus(){this.yh=document.activeElement;var a;_.Lp.Bh&&(a=this.qh.getBoundingClientRect());if(this.get("disableAutoPan"))bL(this,this.Oj);else{var b=_.yw(this.qh);if(b.length){b=b[0];a=a||this.qh.getBoundingClientRect();var c=b.getBoundingClientRect();bL(this,c.bottom<=a.bottom&&c.right<=a.right?
b:this.Oj)}else bL(this,this.rh.element)}}};var LMa=class{constructor(a,b,c){this.model=a;this.isOpen=!0;this.qh=this.sh=this.Rh=null;this.Pi=[];var d=a.get("shouldFocus");this.th=GMa(b,d,a.ct);var e=b.__gm;(d=b instanceof _.Jn)&&c?c.then(h=>{this.isOpen&&(this.Rh=h,this.qh=new _.PI(k=>{this.sh=new _.YA(b,h,k,()=>{});h.Nj(this.sh);return this.sh}),this.qh.bindTo("latLngPosition",a,"position"),OMa(this))}):(this.qh=new _.PI,this.qh.bindTo("latLngPosition",a,"position"),this.qh.bindTo("center",e,"projectionCenterQ"),this.qh.bindTo("zoom",e),
this.qh.bindTo("offset",e),this.qh.bindTo("projection",b),this.qh.bindTo("focus",b,"position"),OMa(this));this.wh=d?a.infoWindow.get("logAsInternal")?148284:148285:null;var f=new _.CI(["scale"],"visible",h=>h==null||h>=.3);this.qh&&f.bindTo("scale",this.qh);var g=this.th;g.set("logAsInternal",!!a.infoWindow.get("logAsInternal"));g.bindTo("ariaLabel",a);g.bindTo("zIndex",a);g.bindTo("layoutPixelBounds",e,"pixelBounds");g.bindTo("disableAutoPan",a);g.bindTo("pendingFocus",a);g.bindTo("maxWidth",a);
g.bindTo("minWidth",a);g.bindTo("content",a);g.bindTo("headerContent",a);g.bindTo("headerDisabled",a);g.bindTo("pixelOffset",a);g.bindTo("visible",f);this.rh=new _.yp(()=>{if(b instanceof _.Jn)if(this.Rh){var h=a.get("position");h&&_.wna(b,this.Rh,new _.Pn(h),KMa(g))}else c.then(()=>{this.rh.start()});else(h=g.get("pixelBounds"))?_.un(e,"pantobounds",h):this.rh.start()},150);if(d){let h=null;this.Pi.push(_.sn(a,"position_changed",()=>{var k=a.get("position");!k||a.get("disableAutoPan")||k.equals(h)||
(this.rh.start(),h=k)}))}else a.get("disableAutoPan")||this.rh.start();g.set("open",!0);this.Pi.push(_.hn(g,"domready",()=>{a.trigger("domready")}));this.Pi.push(_.hn(g,"visible",()=>{a.trigger("visible")}));this.Pi.push(_.hn(g,"closeclick",()=>{a.close();a.trigger("closeclick")}));this.Pi.push(_.sn(a,"pixelposition_changed",()=>{NMa(this)}));this.wh&&_.M(b,this.wh)}close(){if(this.isOpen){this.isOpen=!1;this.model.trigger("close");for(var a of this.Pi)_.kn(a);this.Pi.length=0;this.rh.stop();this.rh.dispose();
this.Rh&&this.sh&&this.Rh.ym(this.sh);a=this.th;a.unbindAll();a.set("open",!1);a.dispose();this.qh&&this.qh.unbindAll()}}};_.Gl("infowindow",{pL:function(a){var b=null;_.sn(a,"map_changed",function d(){var e=a.get("map");b&&(b.uG.qh.delete(a),b.cP.close(),b=null);if(e){let f=e.__gm;f.get("panes")?f.get("innerContainer")?(b={cP:MMa(a,e,e instanceof _.Jn?f.rh.then(({Rh:g})=>g):void 0),uG:QMa(e)},EMa(b.uG,a)):_.rn(f,"innercontainer_changed",d):_.rn(f,"panes_changed",d)}})}});});
